### ISSUE TITLE
add-source = Broken Pipe 💥

### ISSUE THREAD

**Issue by theprojectsomething** [mapbox/tilesets-cli#76] opened 2020-06-23 10:20 UTC
Running into some obtuse errors while attempting to `add-source` (actually update a source). Quite possibly my own fault as I'm on macOS, seem to have 3 versions of python installed, and have no idea about python.

Attempting to upload a 60mb non-ld geojson. Noted a comment from @Gerdie in #31 suggesting that "me-too's" should open a new issue with some further detail.

Have fallen back on this library as a last resort to sidestep a duplicate id issue in mapbox studio. Any help would be much appreciated! Note below my token is included in an environment variable - get the same result as an argument.

```sh
tilesets add-source citizensgbr citizensgbr.2avtrk3p GBR_Features.geojson
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tilesets", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mapbox_tilesets/scripts/cli.py", line 502, in add_source
    "Content-type": m.content_type,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))```

**Comment by gitalink** [comment] 2020-07-08 15:43
Hi @theprojectsomething, have you figured out this issue or a workaround? I am having a similar issue, opened a new ticket for it.

**Comment by CarlosMecha** [comment] 2020-07-08 15:52
Hi @gitalink and @theprojectsomething ! We have schedule this issue for next week's bug rotation. We'll keep the ticket up to date.

**Comment by vknoppkewetzel** [comment] 2020-07-08 20:21
I ran into this and had some thoughts:
- does this relate to size of the dataset? I think people may also already have asked this
- second question is... are these geojsons exported from QGIS? Is it possible a QGIS export is affecting geojsons somehow? This also maybe doesn't make sense but I don't understand how this only happened with some geojsons and not others. And did export a couple out of geojson when I ran into this error, so I figured I may as well write this down

**Comment by gitalink** [comment] 2020-07-08 21:04
I got mine uploaded when I passed my token with --token flag. It might have
been an issue with my token credentials.

**Comment by theprojectsomething** [comment] 2020-07-09 00:53
Hi @gitalink at the time of writing I was attempting to circumvent a duplicate ID issue in mapbox studio (ended up [working around this separately](https://github.com/mapbox/mapbox-gl-js/issues/8284#issuecomment-648085228)). Haven't had a chance to return to the tilesets-cli workflow. I had tried using the token flag with no luck - did you end up getting it fully resolved with this?

@vknoppkewetzel no idea re. filesize, tho I am attempting to update a tileset previously created in studio. This particular dataset hadn't been exported from QGIS.

Cheers!

**Comment by vknoppkewetzel** [comment] 2020-07-09 13:01
oh @theprojectsomething thank you for your response! I was adding to the ticket (happened to me too) and noting some commentary for the team checking this out, however that is some good detail from your end as well. 

- All the best ✨

**Comment by ericcarlschwartz** [comment] 2020-07-14 17:47
Hi @theprojectsomething @vknoppkewetzel @gitalink, I'm going to be investigating this this week! Could you let me know the following for when you ran into this:

- tilesets-cli version
- python version 
- approximate source size

I've been having trouble reproducing this on my own so far.

**Comment by theprojectsomething** [comment] 2020-07-14 20:55
Hi @ericcarlschwartz good timing (I'm away from today) and good luck:
- tilesets-cli 1.1.0.dev0
- python 3.7.7 (also have 3.6.6 and 2.7 installed, macOS) 
- source is a 60mb non-ld geojson (validated)

**Comment by CarlosMecha** [comment] 2020-07-21 16:40
The tilesets team is trying to reproduce the issue. We'll post an update as soon as we have it.

**Comment by jseppi** [comment] 2020-07-29 19:23
I get a `BrokenPipeError: [Errno 32] Broken pipe` when I try to use `tilesets add-source ...` **_with a username that doesn't match the token in `$MAPBOX_ACCESS_TOKEN`_**.

Here's my `mapbox-tilesets` version from my `Pipfile.lock`:

```json
"mapbox-tilesets": {
    "hashes": [
        "sha256:1879bed1da7f885aab7add61a98f647c15ac7ad85fbf6cf04b7b3ddb55f55afe",
        "sha256:c306ab0cdbda4625ffb409e7d1226829bdba31bd6ecab67f2750c46d63002181"
    ],
    "index": "pypi",
    "version": "==1.2.1.dev0"
}
```

Here's the 1.3 MB line-delimited geojson file I'm attempting to use (renamed with `.txt` at the end so I could upload): 
[simple-rivers.geojson-ld.txt](https://github.com/mapbox/tilesets-cli/files/4996940/simple-rivers.geojson-ld.txt)

Here's the full command exception output from my terminal:

```sh
$ pipenv run tilesets add-source jseppi simple-rivers ./data/simple-rivers.geojson-ld  
upload progress  [===========-----------------------------------------------------------------------------]   12%
Traceback (most recent call last):
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/bin/tilesets", line 8, in <module>
    sys.exit(cli())
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/mapbox_tilesets/scripts/cli.py", line 547, in add_source
    resp = s.post(
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

When I used a smaller source file (23 KB), instead of a `BrokenPipe` error, I got a `Not found` error:

```sh
$ pipenv run tilesets add-source jseppi ne-lakes ./data/ne_110m_lakes.geojson
Traceback (most recent call last):
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/bin/tilesets", line 8, in <module>
    sys.exit(cli())
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jamesseppi/.local/share/virtualenvs/try-mts-mNezwtXd/lib/python3.8/site-packages/mapbox_tilesets/scripts/cli.py", line 559, in add_source
    raise errors.TilesetsError(resp.text)
mapbox_tilesets.errors.TilesetsError: {"message":"Not Found"}
```

Perhaps the CLI needs to check that the access token's username matches the username provided in the command?

Or, could the command get rid of the username field altogether and instead use the one in the provided token?

**Comment by ericfischer** [comment] 2020-08-03 18:19
The wrong-username case is reproducible for me with a large source (the 1.2GB `tl_2019_06_tabblock10.shp.ldjson`):

```
tilesets add-source --no-validation slkdfjslf places tecumseh/tl_2019_06_tabblock10.shp.ldjson
```

which fails for me with a chain of broken pipe stack traces, while the 648K `ne_110m_populated_places.shp.json` reports unknown or mismatched usernames:

```
tilesets add-source ksdflksdjf places ne/ne_110m_populated_places.shp.json
mapbox_tilesets.errors.TilesetsError: {"message":"No such user"}
````

and

```
tilesets add-source mapbox places ne/ne_110m_populated_places.shp.json
mapbox_tilesets.errors.TilesetsError: {"message":"Not Found"}
```

I think `tilesets` is trying to send the entire source before it reads and reports any error messages from the service side, and there is a broken pipe because the service hangs up after it reports an error, while the client keeps trying to send more of the source.

**Comment by ericfischer** [comment] 2020-08-03 19:18
Adding a response handler callback on the client side doesn't seem to help, so I think the problem may be on the service side. Perhaps it is buffering the output for too long instead of sending it before the socket closes.

**Comment by ericfischer** [comment] 2020-08-04 18:09
Talking to the API directly with `curl`, the 404 and error message *are* sent quickly, so the fault is on the client side for continuing to try to post after already getting a response.

**Comment by ericfischer** [comment] 2020-08-04 20:28
[This ticket](https://github.com/psf/requests/issues/2422) is full of comments from people having the same problem, and it sounds like there may be no way for `requests` to receive the response before trying to post the entire file.

**Comment by ericfischer** [comment] 2020-08-04 20:31
Maybe we can at least do another no-op request first to validate the username and the token, so that the user gets a reasonable error instead of a mysterious one.

**Comment by CarlosMecha** [comment] 2020-08-10 16:10
@ericfischer can we deploy and close this ticket today?

**Closed** 2020-08-18 21:27 UTC
Labels: bug, bugs-maintenance
